-- UK-AQ Aiven PostGIS schema for PCON + LA boundaries.
-- Stores GSS codes in *_code columns; versions are text for flexible labels (e.g., "2024").

create extension if not exists postgis;

create table if not exists pcon_boundaries (
  id bigint generated by default as identity primary key,
  pcon_code text not null,
  pcon_name text,
  pcon_version text not null,
  geometry geometry(MultiPolygon, 4326) not null,
  created_at timestamptz default now()
);

create unique index if not exists pcon_boundaries_code_version_uidx
  on pcon_boundaries(pcon_code, pcon_version);
create index if not exists pcon_boundaries_version_idx
  on pcon_boundaries(pcon_version);
create index if not exists pcon_boundaries_geom_idx
  on pcon_boundaries using gist (geometry);

create table if not exists la_boundaries (
  id bigint generated by default as identity primary key,
  la_code text not null,
  la_name text,
  la_version text not null,
  geometry geometry(MultiPolygon, 4326) not null,
  created_at timestamptz default now()
);

create unique index if not exists la_boundaries_code_version_uidx
  on la_boundaries(la_code, la_version);
create index if not exists la_boundaries_version_idx
  on la_boundaries(la_version);
create index if not exists la_boundaries_geom_idx
  on la_boundaries using gist (geometry);
