-- Obs AQI DB v0.2.0 core additive catch-up
-- Purpose: bring uk_aq_core mirror/reference tables up to the v0.2.0 core shape
-- without touching uk_aq_core.observations, which does not exist in Obs AQI DB.
-- Safe to run in Supabase SQL editor on Obs AQI DB.

begin;

create extension if not exists postgis;
create extension if not exists pgcrypto;

create schema if not exists uk_aq_core;
set search_path = uk_aq_core, public, pg_catalog;

-- v0.2.0 network model
create table if not exists networks (
  id bigint generated by default as identity primary key,
  network_code text not null,
  display_name text not null,
  ingest_enabled boolean not null default true,
  public_display_enabled boolean not null default false,
  default_priority integer not null default 100,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists networks_network_code_uidx
  on networks(network_code);

create table if not exists station_matches (
  id bigint generated by default as identity primary key,
  match_key text,
  match_name text,
  latitude double precision,
  longitude double precision,
  geometry geography(Point, 4326),
  match_method text,
  match_confidence numeric,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table station_matches
  add column if not exists match_key text;

create unique index if not exists station_matches_match_key_uidx
  on station_matches(match_key)
  where match_key is not null;

create index if not exists station_matches_geometry_idx
  on station_matches using gist (geometry);

-- Connectors v0.2.0 columns. Obs AQI already has most old connector columns.
alter table connectors
  add column if not exists default_network_id bigint,
  add column if not exists station_display_name_template text,
  add column if not exists overwrite_station_name boolean default true,
  add column if not exists poll_timeseries_batch_size integer,
  add column if not exists stations_bbox_supported boolean default true,
  add column if not exists timeseries_station_filter_supported boolean default true,
  add column if not exists last_polled_at timestamptz,
  add column if not exists last_run_start timestamptz,
  add column if not exists last_run_end timestamptz,
  add column if not exists last_run_status text,
  add column if not exists last_run_message text,
  add column if not exists config jsonb not null default '{}'::jsonb,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

-- Stations v0.2.0 columns.
alter table stations
  add column if not exists network_id bigint,
  add column if not exists match_id bigint,
  add column if not exists priority integer not null default 100,
  add column if not exists station_device_ref text,
  add column if not exists description text,
  add column if not exists photo_url text,
  add column if not exists sensor_height_m numeric,
  add column if not exists distance_to_road_m numeric,
  add column if not exists is_indoor boolean,
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists station_initial_metadata (
  station_id bigint primary key references stations(id) on delete cascade,
  attributes jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Observed properties and timeseries v0.2.0 columns used by mirror/core sync.
alter table observed_properties
  add column if not exists display_order integer,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

alter table timeseries
  add column if not exists observed_property_id bigint,
  add column if not exists status text,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

-- Deliberately no ALTER TABLE observations here.
-- Obs AQI DB does not have uk_aq_core.observations.

do $$
begin
  if to_regclass('uk_aq_core.connectors') is not null
     and to_regclass('uk_aq_core.networks') is not null
     and not exists (
       select 1
       from pg_constraint
       where conrelid = 'uk_aq_core.connectors'::regclass
         and conname = 'connectors_default_network_id_fkey'
     ) then
    alter table connectors
      add constraint connectors_default_network_id_fkey
      foreign key (default_network_id)
      references networks(id)
      on delete set null
      not valid;
  end if;

  if to_regclass('uk_aq_core.stations') is not null
     and to_regclass('uk_aq_core.networks') is not null
     and not exists (
       select 1
       from pg_constraint
       where conrelid = 'uk_aq_core.stations'::regclass
         and conname = 'stations_network_id_fkey'
     ) then
    alter table stations
      add constraint stations_network_id_fkey
      foreign key (network_id)
      references networks(id)
      not valid;
  end if;

  if to_regclass('uk_aq_core.stations') is not null
     and to_regclass('uk_aq_core.station_matches') is not null
     and not exists (
       select 1
       from pg_constraint
       where conrelid = 'uk_aq_core.stations'::regclass
         and conname = 'stations_match_id_fkey'
     ) then
    alter table stations
      add constraint stations_match_id_fkey
      foreign key (match_id)
      references station_matches(id)
      on delete set null
      not valid;
  end if;

  if to_regclass('uk_aq_core.timeseries') is not null
     and to_regclass('uk_aq_core.observed_properties') is not null
     and not exists (
       select 1
       from pg_constraint
       where conrelid = 'uk_aq_core.timeseries'::regclass
         and conname = 'timeseries_observed_property_id_fkey'
     ) then
    alter table timeseries
      add constraint timeseries_observed_property_id_fkey
      foreign key (observed_property_id)
      references observed_properties(id)
      not valid;
  end if;
end
$$;

-- v0.2.0 indexes, excluding anything on observations.
create unique index if not exists stations_connector_station_ref_v020_uidx
  on stations(connector_id, station_ref);
create unique index if not exists timeseries_connector_timeseries_ref_v020_uidx
  on timeseries(connector_id, timeseries_ref);

create index if not exists connectors_default_network_id_idx
  on connectors(default_network_id);
create index if not exists networks_public_display_enabled_idx
  on networks(network_code)
  where public_display_enabled;
create index if not exists stations_connector_id_v020_idx
  on stations(connector_id);
create index if not exists stations_network_id_idx
  on stations(network_id);
create index if not exists stations_match_priority_idx
  on stations(match_id, priority);
create index if not exists stations_la_code_v020_idx
  on stations(la_code);
create index if not exists stations_pcon_code_v020_idx
  on stations(pcon_code);
create index if not exists stations_removed_at_idx
  on stations(removed_at)
  where removed_at is not null;
create index if not exists observed_properties_display_order_idx
  on observed_properties(display_order, code);
create index if not exists timeseries_observed_property_id_idx
  on timeseries(observed_property_id);

create or replace function uk_aq_touch_v020_updated_at()
returns trigger
language plpgsql
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgrelid = 'uk_aq_core.networks'::regclass
      and tgname = 'networks_touch_updated_at'
      and not tgisinternal
  ) then
    create trigger networks_touch_updated_at
    before update on networks
    for each row execute function uk_aq_touch_v020_updated_at();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgrelid = 'uk_aq_core.connectors'::regclass
      and tgname = 'connectors_touch_updated_at'
      and not tgisinternal
  ) then
    create trigger connectors_touch_updated_at
    before update on connectors
    for each row execute function uk_aq_touch_v020_updated_at();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgrelid = 'uk_aq_core.station_matches'::regclass
      and tgname = 'station_matches_touch_updated_at'
      and not tgisinternal
  ) then
    create trigger station_matches_touch_updated_at
    before update on station_matches
    for each row execute function uk_aq_touch_v020_updated_at();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgrelid = 'uk_aq_core.stations'::regclass
      and tgname = 'stations_touch_updated_at'
      and not tgisinternal
  ) then
    create trigger stations_touch_updated_at
    before update on stations
    for each row execute function uk_aq_touch_v020_updated_at();
  end if;
end
$$;

commit;
