-- UK AQ v0.2.0 canonical core schema.
-- Clean/bootstrap DDL for the hard-cut target model.
-- Existing databases must use migrations/v0.2.0 instead of this file.

create extension if not exists postgis;
create extension if not exists pgcrypto;

create schema if not exists uk_aq_core;
set search_path = uk_aq_core, public, pg_catalog;

create table if not exists networks (
  id bigint generated by default as identity primary key,
  network_code text not null,
  display_name text not null,
  network_type text not null,
  ingest_enabled boolean not null default true,
  public_display_enabled boolean not null default false,
  default_priority integer not null default 100,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint networks_network_code_key unique (network_code),
  constraint networks_network_type_check
    check (network_type in ('official', 'community', 'aggregator'))
);

create table if not exists connectors (
  id integer generated by default as identity primary key,
  connector_code text not null,
  label text not null,
  display_name text,
  service_url text,
  default_network_id bigint references networks(id) on delete set null,
  station_display_name_template text,
  overwrite_station_name boolean default true,
  poll_enabled boolean not null default true,
  poll_interval_minutes integer not null default 60,
  poll_window_hours integer not null default 6,
  poll_timeseries_batch_size integer,
  scheduler_backend text not null default 'supabase_function',
  stations_bbox_supported boolean default true,
  timeseries_station_filter_supported boolean default true,
  last_polled_at timestamptz,
  last_run_start timestamptz,
  last_run_end timestamptz,
  last_run_status text,
  last_run_message text,
  config jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint connectors_connector_code_key unique (connector_code)
);

create table if not exists station_matches (
  id bigint generated by default as identity primary key,
  match_key text,
  match_name text,
  latitude double precision,
  longitude double precision,
  geometry geography(Point, 4326),
  match_method text,
  match_confidence numeric,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists stations (
  id bigint generated by default as identity primary key,
  connector_id integer not null references connectors(id) on delete cascade,
  network_id bigint not null references networks(id),
  match_id bigint references station_matches(id) on delete set null,
  priority integer not null default 100,
  station_ref text not null,
  service_ref text default 'default',
  label text not null,
  station_name text,
  station_device_ref text,
  station_type text,
  station_exposure text,
  description text,
  photo_url text,
  sensor_height_m numeric,
  distance_to_road_m numeric,
  is_indoor boolean,
  region text,
  la_code text,
  la_version text,
  pcon_code text,
  pcon_version text,
  latitude double precision,
  longitude double precision,
  geometry geography(Point, 4326),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz,
  removed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stations_connector_station_ref_key unique (connector_id, station_ref)
);

create table if not exists station_initial_metadata (
  station_id bigint primary key references stations(id) on delete cascade,
  attributes jsonb not null default '{}'::jsonb,
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists observed_properties (
  id bigint generated by default as identity primary key,
  code text not null,
  display_name text not null,
  domain text not null,
  canonical_uom text,
  display_order integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint observed_properties_code_key unique (code),
  constraint observed_properties_domain_check check (domain in ('aq', 'met'))
);

create table if not exists timeseries (
  id integer generated by default as identity primary key,
  connector_id integer not null references connectors(id) on delete cascade,
  station_id bigint not null references stations(id) on delete cascade,
  observed_property_id bigint not null references observed_properties(id),
  timeseries_ref text not null,
  service_ref text,
  label text not null,
  uom text,
  first_value_at timestamptz,
  last_value_at timestamptz,
  last_value double precision,
  status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ended_at timestamptz,
  constraint timeseries_connector_timeseries_ref_key
    unique (connector_id, timeseries_ref)
);

create table if not exists observations (
  timeseries_id integer not null references timeseries(id) on delete cascade,
  observed_at timestamptz not null,
  value double precision,
  status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (timeseries_id, observed_at)
);

create table if not exists uk_aq_ingest_runs (
  id bigint generated by default as identity primary key,
  connector_id integer references connectors(id) on delete set null,
  connector_code text not null,
  network_id bigint references networks(id) on delete set null,
  network_code text,
  run_started_at timestamptz,
  run_ended_at timestamptz,
  run_status text,
  run_message text,
  last_observed_at timestamptz,
  stations_updated integer,
  observations_upserted integer,
  timeseries_updated integer,
  series_polled integer,
  response_status integer,
  response_payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists connectors_default_network_id_idx
  on connectors(default_network_id);
create index if not exists networks_public_display_enabled_idx
  on networks(network_code)
  where public_display_enabled;
create unique index if not exists station_matches_match_key_uidx
  on station_matches(match_key)
  where match_key is not null;

create index if not exists station_matches_geometry_idx
  on station_matches using gist (geometry);
create index if not exists stations_connector_id_idx
  on stations(connector_id);
create index if not exists stations_network_id_idx
  on stations(network_id);
create index if not exists stations_match_priority_idx
  on stations(match_id, priority);
create index if not exists stations_geometry_idx
  on stations using gist (geometry);
create index if not exists stations_la_code_idx
  on stations(la_code);
create index if not exists stations_pcon_code_idx
  on stations(pcon_code);
create index if not exists stations_removed_at_idx
  on stations(removed_at)
  where removed_at is not null;
create index if not exists observed_properties_display_order_idx
  on observed_properties(display_order, code);
create index if not exists timeseries_station_id_idx
  on timeseries(station_id);
create index if not exists timeseries_observed_property_id_idx
  on timeseries(observed_property_id);
create index if not exists timeseries_connector_ended_at_idx
  on timeseries(connector_id, ended_at);
create index if not exists observations_observed_at_idx
  on observations(observed_at);
create index if not exists uk_aq_ingest_runs_connector_run_end_idx
  on uk_aq_ingest_runs(connector_id, run_ended_at desc);
create index if not exists uk_aq_ingest_runs_network_run_end_idx
  on uk_aq_ingest_runs(network_id, run_ended_at desc);

create or replace function uk_aq_touch_updated_at()
returns trigger
language plpgsql
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists networks_touch_updated_at on networks;
create trigger networks_touch_updated_at
before update on networks
for each row execute function uk_aq_touch_updated_at();

drop trigger if exists connectors_touch_updated_at on connectors;
create trigger connectors_touch_updated_at
before update on connectors
for each row execute function uk_aq_touch_updated_at();

drop trigger if exists station_matches_touch_updated_at on station_matches;
create trigger station_matches_touch_updated_at
before update on station_matches
for each row execute function uk_aq_touch_updated_at();

drop trigger if exists stations_touch_updated_at on stations;
create trigger stations_touch_updated_at
before update on stations
for each row execute function uk_aq_touch_updated_at();

create or replace function uk_aq_assign_station_network_default()
returns trigger
language plpgsql
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  if new.network_id is null then
    select c.default_network_id
    into new.network_id
    from connectors c
    where c.id = new.connector_id;

    if new.network_id is null then
      raise exception
        'Station connector_id % has no default_network_id',
        new.connector_id;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists stations_assign_network_default on stations;
create trigger stations_assign_network_default
before insert or update of connector_id, network_id on stations
for each row execute function uk_aq_assign_station_network_default();

drop trigger if exists observed_properties_touch_updated_at on observed_properties;
create trigger observed_properties_touch_updated_at
before update on observed_properties
for each row execute function uk_aq_touch_updated_at();

drop trigger if exists timeseries_touch_updated_at on timeseries;
create trigger timeseries_touch_updated_at
before update on timeseries
for each row execute function uk_aq_touch_updated_at();
