-- UK-AQ history schema (history-only observations in a separate schema).
-- Safe to rerun; uses IF NOT EXISTS where appropriate.

create schema if not exists uk_aq_history;
create schema if not exists uk_aq_core;
create schema if not exists uk_aq_public;
create schema if not exists uk_aq_ops;

create extension if not exists postgis;
create extension if not exists pgcrypto;

set search_path = uk_aq_core, public;

-- Connectors
create table if not exists connectors (
  id integer generated by default as identity primary key,
  connector_code text not null,
  label text not null,
  display_name text,
  service_url text,
  station_display_name_template text,
  overwrite_station_name boolean default true,
  poll_enabled boolean default true,
  poll_interval_minutes int default 60,
  poll_window_hours int default 6,
  poll_timeseries_batch_size int,
  scheduler_backend text not null default 'supabase_function',
  stations_bbox_supported boolean default true,
  timeseries_station_filter_supported boolean default true,
  last_polled_at timestamptz,
  last_run_start timestamptz,
  last_run_end timestamptz,
  last_run_status text,
  last_run_message text,
  created_at timestamptz default now()
);

create unique index if not exists connectors_connector_code_uidx on connectors(connector_code);

alter table if exists connectors
  add column if not exists scheduler_backend text not null default 'supabase_function';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'connectors_scheduler_backend_check'
      and conrelid = 'connectors'::regclass
  ) then
    alter table connectors
      add constraint connectors_scheduler_backend_check
      check (scheduler_backend in ('supabase_function', 'google_cloud_run'));
  end if;
end
$$;

create or replace function connectors_apply_known_defaults()
returns trigger
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.display_name = coalesce(new.display_name, new.label);
  if new.service_url = 'https://uk-air.defra.gov.uk/sos-ukair/api/v1'
     or new.label = 'UK-AIR-SOS' then
    new.stations_bbox_supported = false;
    new.timeseries_station_filter_supported = false;
  end if;
  if new.connector_code = 'sensorcommunity'
     or new.label = 'Sensor.Community' then
    new.overwrite_station_name = false;
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists connectors_apply_known_defaults on connectors;
create trigger connectors_apply_known_defaults
before insert on connectors
for each row execute function connectors_apply_known_defaults();

-- Dependencies required by FK definitions on mirrored tables.
create table if not exists categories (
  id bigint generated by default as identity primary key,
  category_ref text not null,
  label text not null,
  connector_id integer not null references connectors(id) on delete cascade
);

create unique index if not exists categories_connector_ref_uidx on categories(connector_id, category_ref);

create table if not exists observed_properties (
  id bigint generated by default as identity primary key,
  code text not null,
  display_name text not null,
  domain text not null check (domain in ('aq', 'met')),
  canonical_uom text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists observed_properties_code_uidx
  on observed_properties(code);

create index if not exists observed_properties_domain_idx
  on observed_properties(domain);

create or replace function uk_aq_touch_observed_properties_updated_at()
returns trigger
language plpgsql
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists observed_properties_touch_updated_at on observed_properties;
create trigger observed_properties_touch_updated_at
before update on observed_properties
for each row execute function uk_aq_touch_observed_properties_updated_at();

-- Phenomena (mirrored)
create table if not exists phenomena (
  id bigint generated by default as identity primary key,
  label text not null,
  source_label text,
  notation text,
  pollutant_label text,
  observed_property_id bigint references observed_properties(id),
  connector_id integer not null references connectors(id) on delete cascade
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'uk_aq_core'
      and table_name = 'phenomena'
      and column_name = 'eionet_uri'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'uk_aq_core'
      and table_name = 'phenomena'
      and column_name = 'source_label'
  ) then
    alter table uk_aq_core.phenomena
      rename column eionet_uri to source_label;
  end if;
end
$$;

alter table if exists phenomena
  add column if not exists source_label text;

alter table if exists phenomena
  add column if not exists observed_property_id bigint references observed_properties(id);

drop index if exists phenomena_service_eionet_uidx;

create unique index if not exists phenomena_connector_source_label_uidx
  on phenomena(connector_id, source_label);

create index if not exists phenomena_observed_property_idx
  on phenomena(observed_property_id);

create table if not exists offerings (
  id bigint generated by default as identity primary key,
  offering_ref text not null,
  label text not null,
  service_ref text not null,
  connector_id integer not null references connectors(id) on delete cascade
);

create unique index if not exists offerings_connector_ref_uidx
  on offerings(connector_id, service_ref, offering_ref);

create table if not exists features (
  id bigint generated by default as identity primary key,
  feature_ref text not null,
  label text not null,
  geometry geography(Point, 4326),
  service_ref text not null,
  connector_id integer not null references connectors(id) on delete cascade
);

create unique index if not exists features_connector_ref_uidx
  on features(connector_id, service_ref, feature_ref);

create table if not exists procedures (
  id bigint generated by default as identity primary key,
  procedure_ref text not null,
  label text not null,
  raw_formats text[],
  service_ref text not null,
  connector_id integer not null references connectors(id) on delete cascade
);

create unique index if not exists procedures_connector_ref_uidx
  on procedures(connector_id, service_ref, procedure_ref);

-- Stations (mirrored)
create table if not exists stations (
  id bigint generated by default as identity primary key,
  station_ref text not null,
  service_ref text not null,
  label text not null,
  station_name text,
  station_type text,
  station_exposure text,
  region text,
  la_code text,
  la_version text,
  pcon_code text,
  pcon_version text,
  geometry geography(Point, 4326),
  connector_id integer not null references connectors(id) on delete cascade,
  category_id bigint references categories(id),
  first_seen_at timestamptz default now(),
  last_seen_at timestamptz,
  removed_at timestamptz,
  created_at timestamptz default now()
);

-- Timeseries (mirrored)
create table if not exists timeseries (
  id integer generated by default as identity primary key,
  timeseries_ref text not null,
  label text not null,
  uom text,
  station_id bigint references stations(id) on delete cascade,
  service_ref text not null,
  connector_id integer not null references connectors(id) on delete cascade,
  offering_id bigint references offerings(id),
  feature_id bigint references features(id),
  procedure_id bigint references procedures(id),
  phenomenon_id bigint references phenomena(id),
  category_id bigint references categories(id),
  first_value_at timestamptz,
  last_value_at timestamptz,
  last_value double precision,
  extras jsonb,
  rendering_hints jsonb,
  status_intervals jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table if exists timeseries
  add column if not exists updated_at timestamptz default now();

update timeseries
set updated_at = coalesce(updated_at, last_value_at, created_at, now())
where updated_at is null;

create unique index if not exists timeseries_connector_ref_uidx
  on timeseries(connector_id, service_ref, timeseries_ref);
create index if not exists timeseries_station_idx on timeseries(station_id);
create index if not exists timeseries_phenomenon_idx on timeseries(phenomenon_id);
create index if not exists timeseries_phenomenon_station_idx on timeseries(phenomenon_id, station_id);
create index if not exists timeseries_updated_cursor_idx on timeseries(updated_at, id);

create or replace function uk_aq_touch_timeseries_updated_at()
returns trigger
language plpgsql
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists timeseries_touch_updated_at on timeseries;
create trigger timeseries_touch_updated_at
before update on timeseries
for each row execute function uk_aq_touch_timeseries_updated_at();

-- RLS / policies (matching ingest naming/policy shape).
do $$
declare
  t text;
begin
  for t in
    select unnest(ARRAY[
      'connectors',
      'categories',
      'phenomena',
      'offerings',
      'features',
      'procedures',
      'stations',
      'timeseries'
    ]::text[])
  loop
    execute format('alter table uk_aq_core.%I enable row level security', t);
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = 'uk_aq_core' and p.tablename = t and p.policyname = t || '_select_authenticated'
    ) then
      execute format(
        'create policy %I on uk_aq_core.%I for select using (auth.role() in (''authenticated'',''service_role''));',
        t || '_select_authenticated', t
      );
    end if;
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = 'uk_aq_core' and p.tablename = t and p.policyname = t || '_write_service_role'
    ) then
      execute format(
        'create policy %I on uk_aq_core.%I for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'');',
        t || '_write_service_role', t
      );
    end if;
  end loop;
end $$;

-- Service role privileges (matching ingest approach).
grant usage on schema uk_aq_core to service_role;
grant all on all tables in schema uk_aq_core to service_role;
grant all on all sequences in schema uk_aq_core to service_role;
grant execute on all functions in schema uk_aq_core to service_role;

alter default privileges in schema uk_aq_core
  grant all on tables to service_role;
alter default privileges in schema uk_aq_core
  grant all on sequences to service_role;
alter default privileges in schema uk_aq_core
  grant execute on functions to service_role;

set search_path = public;

create table if not exists uk_aq_history.observations (
  connector_id integer not null,
  timeseries_id integer not null,
  observed_at timestamptz not null,
  value double precision
) partition by range (observed_at);

create table if not exists uk_aq_history.observations_default
  partition of uk_aq_history.observations default;

comment on table uk_aq_history.observations_default is
  'Catch-all/default partition for out-of-range rows. Non-zero rows are treated as a maintenance alert signal.';

create index if not exists uk_aq_history_observations_default_observed_at_brin
  on uk_aq_history.observations_default using brin (observed_at);

do $$
declare
  v_today_utc date := (now() at time zone 'UTC')::date;
  v_day date;
  v_partition_name text;
begin
  for v_day in
    select generate_series(v_today_utc - 2, v_today_utc + 3, interval '1 day')::date
  loop
    v_partition_name := format('observations_%s', to_char(v_day, 'YYYYMMDD'));

    execute format(
      'create table if not exists uk_aq_history.%I '
      'partition of uk_aq_history.observations '
      'for values from (%L) to (%L)',
      v_partition_name,
      format('%s 00:00:00+00', v_day),
      format('%s 00:00:00+00', v_day + 1)
    );

    execute format(
      'create index if not exists %I on uk_aq_history.%I using brin (observed_at)',
      v_partition_name || '_observed_at_brin_idx',
      v_partition_name
    );

    if v_day between (v_today_utc - 2) and (v_today_utc + 3) then
      execute format(
        'create unique index if not exists %I on uk_aq_history.%I (connector_id, timeseries_id, observed_at)',
        v_partition_name || '_hot_key_uidx',
        v_partition_name
      );
    else
      execute format(
        'drop index if exists uk_aq_history.%I',
        v_partition_name || '_hot_key_uidx'
      );
    end if;
  end loop;
end $$;

-- RLS: history access is service_role only (Edge Functions / server).
alter table if exists uk_aq_history.observations enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies p
    where p.schemaname = 'uk_aq_history'
      and p.tablename = 'observations'
      and p.policyname = 'uk_aq_history_observations_service_role'
  ) then
    execute
      'create policy uk_aq_history_observations_service_role on uk_aq_history.observations '
      'for all using (auth.role() = ''service_role'') '
      'with check (auth.role() = ''service_role'');';
  end if;
end $$;

create table if not exists uk_aq_ops.db_size_metrics_hourly (
  bucket_hour timestamptz not null,
  database_label text not null check (database_label in ('ingestdb', 'historydb', 'aggdailydb')),
  database_name text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  oldest_observed_at timestamptz,
  source text not null default 'uk_aq_db_size_logger_cloud_run',
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (bucket_hour, database_label)
);

create index if not exists db_size_metrics_hourly_database_label_idx
  on uk_aq_ops.db_size_metrics_hourly (database_label, bucket_hour desc);

create or replace view uk_aq_public.uk_aq_db_size_metrics_hourly as
select
  bucket_hour,
  database_label,
  database_name,
  size_bytes,
  source,
  recorded_at,
  created_at,
  updated_at,
  oldest_observed_at
from uk_aq_ops.db_size_metrics_hourly;
alter view if exists uk_aq_public.uk_aq_db_size_metrics_hourly set (security_invoker = true);

create extension if not exists pg_cron with schema extensions;

-- Schedule daily history observations VACUUM FULL at 05:30 UTC.
select cron.unschedule(jobid)
from cron.job
where jobname = 'uk_aq_history_observations_vacuum_full_0530_utc';

select cron.schedule(
  'uk_aq_history_observations_vacuum_full_0530_utc',
  '30 5 * * *',
  $$vacuum (full, analyze, verbose) uk_aq_history.observations;$$
);

create or replace function uk_aq_ops.uk_aq_db_size_metric_sample_local(
  p_retention_days integer default 120,
  p_recorded_at timestamptz default now(),
  p_source text default 'uk_aq_db_size_logger_pg_cron'
)
returns table (
  rows_upserted int,
  rows_deleted bigint
)
language plpgsql
security definer
set search_path = uk_aq_ops, uk_aq_history, public, pg_catalog
as $$
declare
  v_days integer;
  v_bucket_hour timestamptz;
  v_rows_upserted int := 0;
  v_rows_deleted bigint := 0;
  v_source text;
begin
  v_days := greatest(1, least(coalesce(p_retention_days, 120), 3650));
  v_bucket_hour := date_trunc('hour', coalesce(p_recorded_at, now()));
  v_source := coalesce(nullif(btrim(p_source), ''), 'uk_aq_db_size_logger_pg_cron');

  insert into uk_aq_ops.db_size_metrics_hourly (
    bucket_hour,
    database_label,
    database_name,
    size_bytes,
    oldest_observed_at,
    source,
    recorded_at,
    updated_at
  )
  values (
    v_bucket_hour,
    'historydb',
    current_database()::text,
    (
      select coalesce(sum(pg_database_size(pg_database.datname)), 0)::bigint
      from pg_database
    ),
    (select min(o.observed_at) from uk_aq_history.observations o),
    v_source,
    coalesce(p_recorded_at, now()),
    now()
  )
  on conflict (bucket_hour, database_label) do update set
    database_name = excluded.database_name,
    size_bytes = excluded.size_bytes,
    oldest_observed_at = excluded.oldest_observed_at,
    source = excluded.source,
    recorded_at = excluded.recorded_at,
    updated_at = now();

  get diagnostics v_rows_upserted = row_count;

  delete from uk_aq_ops.db_size_metrics_hourly
  where bucket_hour < now() - make_interval(days => v_days);

  get diagnostics v_rows_deleted = row_count;

  return query select v_rows_upserted, v_rows_deleted;
end;
$$;

select cron.unschedule(jobid)
from cron.job
where jobname = 'uk_aq_history_db_size_metrics_hourly';

select cron.schedule(
  'uk_aq_history_db_size_metrics_hourly',
  '2 * * * *',
  $$select * from uk_aq_ops.uk_aq_db_size_metric_sample_local();$$
);

revoke all on function uk_aq_ops.uk_aq_db_size_metric_sample_local(integer, timestamptz, text) from public;
grant execute on function uk_aq_ops.uk_aq_db_size_metric_sample_local(integer, timestamptz, text) to service_role;

revoke all on uk_aq_public.uk_aq_db_size_metrics_hourly from public;
grant select on uk_aq_public.uk_aq_db_size_metrics_hourly to authenticated;
grant select on uk_aq_public.uk_aq_db_size_metrics_hourly to service_role;

grant usage on schema uk_aq_history to service_role;
grant usage on schema uk_aq_public to service_role;
grant usage on schema uk_aq_ops to service_role;
grant all on table uk_aq_history.observations to service_role;
grant all on table uk_aq_ops.db_size_metrics_hourly to service_role;
