-- uk_aq_core subset for Agg Daily DB.
-- Source of truth copied from ingest schema DDL so mirrored tables match exactly.

create extension if not exists postgis;
create extension if not exists pgcrypto;

create schema if not exists uk_aq_core;
create schema if not exists uk_aq_public;
create schema if not exists uk_aq_aggdaily;

set search_path = uk_aq_core, public;

-- Connectors
create table if not exists connectors (
  id integer generated by default as identity primary key,
  connector_code text not null,
  label text not null,
  display_name text,
  service_url text,
  station_display_name_template text,
  overwrite_station_name boolean default true,
  poll_enabled boolean default true,
  poll_interval_minutes int default 60,
  poll_window_hours int default 6,
  poll_timeseries_batch_size int,
  scheduler_backend text not null default 'supabase_function',
  stations_bbox_supported boolean default true,
  timeseries_station_filter_supported boolean default true,
  last_polled_at timestamptz,
  last_run_start timestamptz,
  last_run_end timestamptz,
  last_run_status text,
  last_run_message text,
  created_at timestamptz default now()
);

create unique index if not exists connectors_connector_code_uidx on connectors(connector_code);

alter table if exists connectors
  add column if not exists scheduler_backend text not null default 'supabase_function';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'connectors_scheduler_backend_check'
      and conrelid = 'connectors'::regclass
  ) then
    alter table connectors
      add constraint connectors_scheduler_backend_check
      check (scheduler_backend in ('supabase_function', 'google_cloud_run'));
  end if;
end
$$;

create or replace function connectors_apply_known_defaults()
returns trigger
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.display_name = coalesce(new.display_name, new.label);
  if new.service_url = 'https://uk-air.defra.gov.uk/sos-ukair/api/v1'
     or new.label = 'UK-AIR-SOS' then
    new.stations_bbox_supported = false;
    new.timeseries_station_filter_supported = false;
  end if;
  if new.connector_code = 'sensorcommunity'
     or new.label = 'Sensor.Community' then
    new.overwrite_station_name = false;
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists connectors_apply_known_defaults on connectors;
create trigger connectors_apply_known_defaults
before insert on connectors
for each row execute function connectors_apply_known_defaults();

-- Dependencies required by FK definitions on mirrored tables.
create table if not exists categories (
  id bigint generated by default as identity primary key,
  category_ref text not null,
  label text not null,
  connector_id integer not null references connectors(id) on delete cascade
);

create unique index if not exists categories_connector_ref_uidx on categories(connector_id, category_ref);

create table if not exists observed_properties (
  id bigint generated by default as identity primary key,
  code text not null,
  display_name text not null,
  domain text not null check (domain in ('aq', 'met')),
  canonical_uom text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists observed_properties_code_uidx
  on observed_properties(code);

create index if not exists observed_properties_domain_idx
  on observed_properties(domain);

create or replace function uk_aq_touch_observed_properties_updated_at()
returns trigger
language plpgsql
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists observed_properties_touch_updated_at on observed_properties;
create trigger observed_properties_touch_updated_at
before update on observed_properties
for each row execute function uk_aq_touch_observed_properties_updated_at();

-- Phenomena (mirrored)
create table if not exists phenomena (
  id bigint generated by default as identity primary key,
  label text not null,
  source_label text,
  notation text,
  pollutant_label text,
  observed_property_id bigint references observed_properties(id),
  connector_id integer not null references connectors(id) on delete cascade
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'uk_aq_core'
      and table_name = 'phenomena'
      and column_name = 'eionet_uri'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'uk_aq_core'
      and table_name = 'phenomena'
      and column_name = 'source_label'
  ) then
    alter table uk_aq_core.phenomena
      rename column eionet_uri to source_label;
  end if;
end
$$;

alter table if exists phenomena
  add column if not exists source_label text;

alter table if exists phenomena
  add column if not exists observed_property_id bigint references observed_properties(id);

drop index if exists phenomena_service_eionet_uidx;

create unique index if not exists phenomena_connector_source_label_uidx
  on phenomena(connector_id, source_label);

create index if not exists phenomena_observed_property_idx
  on phenomena(observed_property_id);

create table if not exists offerings (
  id bigint generated by default as identity primary key,
  offering_ref text not null,
  label text not null,
  service_ref text not null,
  connector_id integer not null references connectors(id) on delete cascade
);

create unique index if not exists offerings_connector_ref_uidx
  on offerings(connector_id, service_ref, offering_ref);

create table if not exists features (
  id bigint generated by default as identity primary key,
  feature_ref text not null,
  label text not null,
  geometry geography(Point, 4326),
  service_ref text not null,
  connector_id integer not null references connectors(id) on delete cascade
);

create unique index if not exists features_connector_ref_uidx
  on features(connector_id, service_ref, feature_ref);

create table if not exists procedures (
  id bigint generated by default as identity primary key,
  procedure_ref text not null,
  label text not null,
  raw_formats text[],
  service_ref text not null,
  connector_id integer not null references connectors(id) on delete cascade
);

create unique index if not exists procedures_connector_ref_uidx
  on procedures(connector_id, service_ref, procedure_ref);

-- Stations (mirrored)
create table if not exists stations (
  id bigint generated by default as identity primary key,
  station_ref text not null,
  service_ref text not null,
  label text not null,
  station_name text,
  station_type text,
  station_exposure text,
  region text,
  la_code text,
  la_version text,
  pcon_code text,
  pcon_version text,
  geometry geography(Point, 4326),
  connector_id integer not null references connectors(id) on delete cascade,
  category_id bigint references categories(id),
  first_seen_at timestamptz default now(),
  last_seen_at timestamptz,
  removed_at timestamptz,
  created_at timestamptz default now()
);

-- Timeseries (mirrored)
create table if not exists timeseries (
  id integer generated by default as identity primary key,
  timeseries_ref text not null,
  label text not null,
  uom text,
  station_id bigint references stations(id) on delete cascade,
  service_ref text not null,
  connector_id integer not null references connectors(id) on delete cascade,
  offering_id bigint references offerings(id),
  feature_id bigint references features(id),
  procedure_id bigint references procedures(id),
  phenomenon_id bigint references phenomena(id),
  category_id bigint references categories(id),
  first_value_at timestamptz,
  last_value_at timestamptz,
  last_value double precision,
  extras jsonb,
  rendering_hints jsonb,
  status_intervals jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table if exists timeseries
  add column if not exists updated_at timestamptz default now();

update timeseries
set updated_at = coalesce(updated_at, last_value_at, created_at, now())
where updated_at is null;

create unique index if not exists timeseries_connector_ref_uidx
  on timeseries(connector_id, service_ref, timeseries_ref);
create index if not exists timeseries_station_idx on timeseries(station_id);
create index if not exists timeseries_phenomenon_idx on timeseries(phenomenon_id);
create index if not exists timeseries_phenomenon_station_idx on timeseries(phenomenon_id, station_id);
create index if not exists timeseries_updated_cursor_idx on timeseries(updated_at, id);

create or replace function uk_aq_touch_timeseries_updated_at()
returns trigger
language plpgsql
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists timeseries_touch_updated_at on timeseries;
create trigger timeseries_touch_updated_at
before update on timeseries
for each row execute function uk_aq_touch_timeseries_updated_at();

-- RLS / policies (matching ingest naming/policy shape).
do $$
declare
  t text;
begin
  for t in
    select unnest(ARRAY[
      'connectors',
      'categories',
      'phenomena',
      'offerings',
      'features',
      'procedures',
      'stations',
      'timeseries'
    ]::text[])
  loop
    execute format('alter table uk_aq_core.%I enable row level security', t);
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = 'uk_aq_core' and p.tablename = t and p.policyname = t || '_select_authenticated'
    ) then
      execute format(
        'create policy %I on uk_aq_core.%I for select using (auth.role() in (''authenticated'',''service_role''));',
        t || '_select_authenticated', t
      );
    end if;
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = 'uk_aq_core' and p.tablename = t and p.policyname = t || '_write_service_role'
    ) then
      execute format(
        'create policy %I on uk_aq_core.%I for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'');',
        t || '_write_service_role', t
      );
    end if;
  end loop;
end $$;

-- Service role privileges (matching ingest approach).
grant usage on schema uk_aq_core to service_role;
grant all on all tables in schema uk_aq_core to service_role;
grant all on all sequences in schema uk_aq_core to service_role;
grant execute on all functions in schema uk_aq_core to service_role;

alter default privileges in schema uk_aq_core
  grant all on tables to service_role;
alter default privileges in schema uk_aq_core
  grant all on sequences to service_role;
alter default privileges in schema uk_aq_core
  grant execute on functions to service_role;

grant usage on schema public to service_role;
grant usage on schema uk_aq_public to service_role;
grant usage on schema uk_aq_aggdaily to service_role;

-- DB size logger RPC (used by ops db-size logger Cloud Run).
create or replace function uk_aq_public.uk_aq_rpc_database_size_bytes()
returns table (
  database_name text,
  size_bytes bigint,
  sampled_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'service_role required';
  end if;

  return query
  select
    current_database()::text as database_name,
    pg_database_size(current_database())::bigint as size_bytes,
    now() as sampled_at;
end;
$$;

revoke all on function uk_aq_public.uk_aq_rpc_database_size_bytes() from public;
grant execute on function uk_aq_public.uk_aq_rpc_database_size_bytes() to service_role;

-- Metadata RPCs for stations_daily mirror verification/sync.
create or replace function uk_aq_public.uk_aq_rpc_info_schema_columns(
  p_schema text default 'uk_aq_core',
  p_table_names text[] default null
)
returns table (
  table_name text,
  column_name text,
  udt_name text,
  is_nullable text,
  column_default text,
  ordinal_position integer
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'service_role required';
  end if;

  return query
  select
    c.table_name::text,
    c.column_name::text,
    c.udt_name::text,
    c.is_nullable::text,
    c.column_default::text,
    c.ordinal_position::integer
  from information_schema.columns c
  where c.table_schema = coalesce(nullif(trim(p_schema), ''), 'uk_aq_core')
    and (p_table_names is null or c.table_name = any(p_table_names))
  order by c.table_name, c.ordinal_position;
end;
$$;

revoke all on function uk_aq_public.uk_aq_rpc_info_schema_columns(text, text[]) from public;
grant execute on function uk_aq_public.uk_aq_rpc_info_schema_columns(text, text[]) to service_role;

create or replace function uk_aq_public.uk_aq_rpc_info_schema_primary_keys(
  p_schema text default 'uk_aq_core',
  p_table_names text[] default null
)
returns table (
  table_name text,
  constraint_name text,
  column_name text,
  ordinal_position integer
)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'service_role required';
  end if;

  return query
  select
    kcu.table_name::text,
    kcu.constraint_name::text,
    kcu.column_name::text,
    kcu.ordinal_position::integer
  from information_schema.table_constraints tc
  join information_schema.key_column_usage kcu
    on tc.constraint_name = kcu.constraint_name
   and tc.table_schema = kcu.table_schema
   and tc.table_name = kcu.table_name
  where tc.table_schema = coalesce(nullif(trim(p_schema), ''), 'uk_aq_core')
    and tc.constraint_type = 'PRIMARY KEY'
    and (p_table_names is null or tc.table_name = any(p_table_names))
  order by kcu.table_name, kcu.constraint_name, kcu.ordinal_position;
end;
$$;

revoke all on function uk_aq_public.uk_aq_rpc_info_schema_primary_keys(text, text[]) from public;
grant execute on function uk_aq_public.uk_aq_rpc_info_schema_primary_keys(text, text[]) to service_role;
