-- Connector-aware observed-property mapping policy.
-- Apply to the CIC-Test ingest DB before hardening uk_aq_rpc_phenomena_upsert.

set search_path = uk_aq_core, public, pg_catalog;

create unique index if not exists observed_properties_id_code_uidx
  on observed_properties(id, code);

create table if not exists observed_property_mappings (
  id bigint generated by default as identity primary key,
  connector_id integer not null references connectors(id) on delete cascade,
  source_label text not null,
  notation text,
  pollutant_label text,
  source_uom text,
  observed_property_id bigint,
  observed_property_code text,
  mapping_kind text not null,
  is_aqi_eligible boolean not null default false,
  is_active boolean not null default true,
  confidence text not null default 'explicit',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint observed_property_mappings_connector_source_key
    unique (connector_id, source_label),
  constraint observed_property_mappings_property_fkey
    foreign key (observed_property_id, observed_property_code)
    references observed_properties(id, code),
  constraint observed_property_mappings_kind_check
    check (
      mapping_kind in (
        'raw_observed_property',
        'derived_index',
        'derived_statistic',
        'meteorological',
        'unknown',
        'ignored'
      )
    ),
  constraint observed_property_mappings_confidence_check
    check (confidence in ('explicit', 'inferred', 'legacy_backfill')),
  constraint observed_property_mappings_property_presence_check
    check (
      (
        mapping_kind in ('raw_observed_property', 'meteorological')
        and observed_property_id is not null
        and observed_property_code is not null
      )
      or
      (
        mapping_kind in ('derived_index', 'derived_statistic', 'unknown', 'ignored')
        and observed_property_id is null
        and observed_property_code is null
      )
    ),
  constraint observed_property_mappings_aqi_eligibility_check
    check (
      not is_aqi_eligible
      or (
        mapping_kind = 'raw_observed_property'
        and observed_property_code in ('pm25', 'pm10', 'no2')
      )
    ),
  constraint observed_property_mappings_raw_uom_check
    check (
      mapping_kind <> 'raw_observed_property'
      or lower(coalesce(source_uom, '')) not in ('daqi', 'index')
    ),
  constraint observed_property_mappings_raw_pollutant_label_check
    check (
      mapping_kind <> 'raw_observed_property'
      or lower(coalesce(pollutant_label, '')) not like 'daqi[_]%'
    )
);

create index if not exists observed_property_mappings_property_idx
  on observed_property_mappings(observed_property_id);

create index if not exists observed_property_mappings_kind_active_idx
  on observed_property_mappings(mapping_kind, is_active);

create index if not exists observed_property_mappings_aqi_eligible_idx
  on observed_property_mappings(connector_id, source_label)
  where is_active and is_aqi_eligible;

create or replace function uk_aq_touch_observed_property_mappings_updated_at()
returns trigger
language plpgsql
set search_path = uk_aq_core, public, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists observed_property_mappings_touch_updated_at
  on observed_property_mappings;
create trigger observed_property_mappings_touch_updated_at
before update on observed_property_mappings
for each row execute function uk_aq_touch_observed_property_mappings_updated_at();

comment on table observed_property_mappings is
  'Connector-specific policy mapping source phenomena to canonical observed properties, including explicit non-raw classifications.';
comment on column observed_property_mappings.mapping_kind is
  'Classification controlling whether a source phenomenon may link to a canonical observed property.';
comment on column observed_property_mappings.is_aqi_eligible is
  'True only for active raw pm25, pm10, or no2 mappings eligible for AQI computation.';

insert into observed_property_mappings (
  connector_id,
  source_label,
  notation,
  pollutant_label,
  source_uom,
  observed_property_id,
  observed_property_code,
  mapping_kind,
  is_aqi_eligible,
  confidence,
  notes
)
select
  c.id,
  seed.source_label,
  seed.notation,
  seed.pollutant_label,
  seed.source_uom,
  op.id,
  seed.observed_property_code,
  seed.mapping_kind,
  seed.is_aqi_eligible,
  'explicit',
  seed.notes
from connectors c
cross join (
  values
    (
      'breathelondon_nodes:pm2.5',
      'PM2.5',
      'pm2.5',
      'ug.m-3',
      'pm25',
      'raw_observed_property',
      true,
      'Breathe London Nodes raw PM2.5 concentration.'
    ),
    (
      'breathelondon_nodes:no2',
      'NO2',
      'no2',
      'ug.m-3',
      'no2',
      'raw_observed_property',
      true,
      'Breathe London Nodes raw NO2 concentration.'
    ),
    (
      'breathelondon_nodes:pm2.5:daqi',
      'PM2.5 DAQI',
      'daqi_pm25',
      'DAQI',
      null,
      'derived_index',
      false,
      'Source-provided DAQI index; intentionally not mapped as a raw pollutant.'
    ),
    (
      'breathelondon_nodes:no2:daqi',
      'NO2 DAQI',
      'daqi_no2',
      'DAQI',
      null,
      'derived_index',
      false,
      'Source-provided DAQI index; intentionally not mapped as a raw pollutant.'
    )
) as seed(
  source_label,
  notation,
  pollutant_label,
  source_uom,
  observed_property_code,
  mapping_kind,
  is_aqi_eligible,
  notes
)
left join observed_properties op
  on op.code = seed.observed_property_code
where c.connector_code = 'blondon_nodes'
on conflict (connector_id, source_label) do update
set
  notation = excluded.notation,
  pollutant_label = excluded.pollutant_label,
  source_uom = excluded.source_uom,
  observed_property_id = excluded.observed_property_id,
  observed_property_code = excluded.observed_property_code,
  mapping_kind = excluded.mapping_kind,
  is_aqi_eligible = excluded.is_aqi_eligible,
  is_active = true,
  confidence = excluded.confidence,
  notes = excluded.notes
where (
  observed_property_mappings.notation,
  observed_property_mappings.pollutant_label,
  observed_property_mappings.source_uom,
  observed_property_mappings.observed_property_id,
  observed_property_mappings.observed_property_code,
  observed_property_mappings.mapping_kind,
  observed_property_mappings.is_aqi_eligible,
  observed_property_mappings.is_active,
  observed_property_mappings.confidence,
  observed_property_mappings.notes
) is distinct from (
  excluded.notation,
  excluded.pollutant_label,
  excluded.source_uom,
  excluded.observed_property_id,
  excluded.observed_property_code,
  excluded.mapping_kind,
  excluded.is_aqi_eligible,
  true,
  excluded.confidence,
  excluded.notes
);

alter table observed_property_mappings enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'uk_aq_core'
      and tablename = 'observed_property_mappings'
      and policyname = 'observed_property_mappings_select_authenticated'
  ) then
    create policy observed_property_mappings_select_authenticated
      on observed_property_mappings
      for select
      using ((select auth.role()) in ('authenticated', 'service_role'));
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'uk_aq_core'
      and tablename = 'observed_property_mappings'
      and policyname = 'observed_property_mappings_write_service_role'
  ) then
    create policy observed_property_mappings_write_service_role
      on observed_property_mappings
      for all
      using ((select auth.role()) = 'service_role')
      with check ((select auth.role()) = 'service_role');
  end if;
end
$$;

grant all on table observed_property_mappings to service_role;
grant select on table observed_property_mappings to authenticated;
grant usage, select on all sequences in schema uk_aq_core to service_role;
