-- uk_aq_raw schema (split from uk_air_quality_schema.sql)
create schema if not exists uk_aq_raw;
set search_path = uk_aq_raw, uk_aq_core, public;

create table if not exists uk_air_sos_site_register (
  id bigint generated by default as identity primary key,
  uk_air_id text not null,
  eu_site_id text,
  emep_site_id text,
  site_name text,
  environment_type text,
  zone text,
  start_date date,
  end_date date,
  latitude double precision,
  longitude double precision,
  northing double precision,
  easting double precision,
  altitude_m double precision,
  networks text[] not null default '{}'::text[],
  aurn_pollutants_measured text,
  site_description text,
  source_url text,
  source_file text,
  snapshot_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists uk_air_sos_site_register_uk_air_id_idx
  on uk_air_sos_site_register(uk_air_id);
create index if not exists uk_air_sos_site_register_snapshot_idx
  on uk_air_sos_site_register(snapshot_at);
create index if not exists uk_air_sos_site_register_networks_gin_idx
  on uk_air_sos_site_register using gin (networks);
create unique index if not exists uk_air_sos_site_register_snapshot_uidx
  on uk_air_sos_site_register(uk_air_id, snapshot_at);

create table if not exists laqn_site_register (
  id bigint generated by default as identity primary key,
  site_ref text not null,
  label text,
  station_name text,
  station_type text,
  station_exposure text,
  local_authority text,
  network_label text,
  networks text[] not null default '{}'::text[],
  latitude double precision,
  longitude double precision,
  lat_offset double precision,
  lon_offset double precision,
  site_url text,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  removed_at timestamptz,
  source_url text,
  source_file text,
  snapshot_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists laqn_site_register_site_ref_idx
  on laqn_site_register(site_ref);
create index if not exists laqn_site_register_snapshot_idx
  on laqn_site_register(snapshot_at);
create index if not exists laqn_site_register_networks_gin_idx
  on laqn_site_register using gin (networks);
create unique index if not exists laqn_site_register_snapshot_uidx
  on laqn_site_register(site_ref, snapshot_at);

create table if not exists uk_air_sos_station_refs (
  station_id bigint primary key references stations(id) on delete cascade,
  uk_air_id text not null,
  match_method text,
  match_distance_m double precision,
  source_snapshot_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists uk_air_sos_station_refs_uk_air_id_idx
  on uk_air_sos_station_refs(uk_air_id);
create index if not exists uk_air_sos_station_refs_snapshot_idx
  on uk_air_sos_station_refs(source_snapshot_at);


create table if not exists breathelondon_station_checkpoints (
  station_id bigint primary key references stations(id) on delete cascade,
  next_due_at timestamptz,
  last_observed_at timestamptz,
  ingest_lag_samples int[] not null default '{}'::int[],
  last_polled_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists breathelondon_station_checkpoints_next_due_at_idx
  on breathelondon_station_checkpoints(next_due_at);
create index if not exists breathelondon_station_checkpoints_last_polled_at_idx
  on breathelondon_station_checkpoints(last_polled_at);

create table if not exists erg_laqn_station_checkpoints (
  station_id bigint primary key references stations(id) on delete cascade,
  last_polled_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists erg_laqn_station_checkpoints_last_polled_idx
  on erg_laqn_station_checkpoints(last_polled_at);

create table if not exists uk_air_sos_timeseries_checkpoints (
  timeseries_id integer primary key references timeseries(id) on delete cascade,
  last_polled_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create index if not exists uk_air_sos_timeseries_checkpoints_last_polled_at_idx
  on uk_air_sos_timeseries_checkpoints(last_polled_at);

create table if not exists uk_air_sos_station_checkpoints (
  station_id bigint primary key references stations(id) on delete cascade,
  next_due_at timestamptz,
  last_observed_at timestamptz,
  ingest_lag_samples int[] not null default '{}'::int[],
  last_polled_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists uk_air_sos_station_checkpoints_next_due_idx
  on uk_air_sos_station_checkpoints(next_due_at);
create index if not exists uk_air_sos_station_checkpoints_last_polled_idx
  on uk_air_sos_station_checkpoints(last_polled_at);
create index if not exists uk_air_sos_station_checkpoints_last_observed_idx
  on uk_air_sos_station_checkpoints(last_observed_at);

create table if not exists openaq_station_checkpoints (
  station_id bigint primary key references stations(id) on delete cascade,
  next_due_at timestamptz,
  last_observed_at timestamptz,
  observ_interval_samples int[] not null default '{}'::int[],
  ingest_lag_samples int[] not null default '{}'::int[],
  last_polled_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists openaq_station_checkpoints_next_due_at_idx
  on openaq_station_checkpoints(next_due_at);
create index if not exists openaq_station_checkpoints_last_polled_at_idx
  on openaq_station_checkpoints(last_polled_at);

create table if not exists openaq_timeseries_checkpoints (
  station_id bigint not null references stations(id) on delete cascade,
  timeseries_id integer not null references timeseries(id) on delete cascade,
  next_due_at timestamptz,
  last_observed_at timestamptz,
  ingest_lag_samples int[] not null default '{}'::int[],
  last_polled_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (station_id, timeseries_id)
);

create index if not exists openaq_timeseries_checkpoints_next_due_at_idx
  on openaq_timeseries_checkpoints(next_due_at);
create index if not exists openaq_timeseries_checkpoints_last_polled_at_idx
  on openaq_timeseries_checkpoints(last_polled_at);
create index if not exists openaq_timeseries_checkpoints_timeseries_id_idx
  on openaq_timeseries_checkpoints(timeseries_id);

create table if not exists observation_rpc_metrics_minute (
  bucket_minute timestamptz not null,
  endpoint text not null,
  calls bigint not null default 0,
  rows_input bigint not null default 0,
  payload_bytes bigint not null default 0,
  rows_upserted bigint not null default 0,
  duration_ms_sum bigint not null default 0,
  duration_ms_max int not null default 0,
  primary key (bucket_minute, endpoint)
);

create index if not exists observation_rpc_metrics_minute_endpoint_idx
  on observation_rpc_metrics_minute (endpoint, bucket_minute desc);

-- Local Authority boundaries (used to persist station LA codes)

create table if not exists error_logs (
  id uuid default gen_random_uuid() primary key,
  created_at timestamptz default now(),
  source text not null,
  severity text not null,
  message text not null,
  stack text,
  context jsonb,
  connector_id integer references connectors(id) on delete set null,
  station_id bigint references stations(id) on delete set null,
  timeseries_id integer references timeseries(id) on delete set null,
  dropbox_path text
);
create index if not exists error_logs_created_at_idx on error_logs(created_at desc);
create index if not exists error_logs_source_idx on error_logs(source);
create index if not exists error_logs_connector_idx on error_logs(connector_id);

-- PM2.5 Population Exposure Indicator progress (PERT)

-- RLS policies for uk_aq_raw tables.
do $$
declare
  t text;
begin
  for t in
    select unnest(ARRAY['uk_air_sos_site_register','laqn_site_register','uk_air_sos_station_refs','breathelondon_station_checkpoints','erg_laqn_station_checkpoints','uk_air_sos_timeseries_checkpoints','uk_air_sos_station_checkpoints','openaq_station_checkpoints','openaq_timeseries_checkpoints','observation_rpc_metrics_minute','error_logs']::text[])
  loop
    execute format('alter table uk_aq_raw.%I enable row level security', t);
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = 'uk_aq_raw' and p.tablename = t and p.policyname = t || '_select_service_role'
    ) then
      execute format(
        'create policy %I on uk_aq_raw.%I for select using (auth.role() = ''service_role'');',
        t || '_select_service_role', t
      );
    end if;
    if not exists (
      select 1 from pg_policies p
      where p.schemaname = 'uk_aq_raw' and p.tablename = t and p.policyname = t || '_write_service_role'
    ) then
      execute format(
        'create policy %I on uk_aq_raw.%I for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'');',
        t || '_write_service_role', t
      );
    end if;
  end loop;
end $$;

-- Service role privileges (required for PostgREST access to non-public schemas).
grant usage on schema uk_aq_raw to service_role;
grant all on all tables in schema uk_aq_raw to service_role;
grant all on all sequences in schema uk_aq_raw to service_role;
grant execute on all functions in schema uk_aq_raw to service_role;

alter default privileges in schema uk_aq_raw
  grant all on tables to service_role;
alter default privileges in schema uk_aq_raw
  grant all on sequences to service_role;
alter default privileges in schema uk_aq_raw
  grant execute on functions to service_role;

-- Schema USAGE for PostgREST schema cache (tables remain protected by RLS).
grant usage on schema uk_aq_raw to anon, authenticated;
